name: Deploy
on:
  push:
    branches:
      - master
      - main

env:
  SERVER_HOST: ${{ vars.SERVER_HOST }}
  SERVER_USER: ${{ vars.SERVER_USER }}
  SERVER_PATH: ${{ vars.SERVER_PATH }}
  SERVER_PORT: ${{ vars.SERVER_PORT }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ env.SERVER_PORT }} -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync --archive --compress --progress --delete . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }} --filter=":- .gitignore"
     
      - name: Update .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ env.SERVER_PORT }}
          script: |
            cd ${{ env.SERVER_PATH }}
            touch ./core/.env
            echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> ./core/.env
            echo DATABASE_BASENAME=${{ secrets.DATABASE_BASENAME }} >> ./core/.env
            echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} >> ./core/.env
            echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> ./core/.env
            cat ./core/.env
            chmod 777 ./core/.env
